bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

logging:
  level:
    root: INFO
    gpb.itfactory.productadvisortelegrambot.bot.config: ERROR
    gpb.itfactory.productadvisortelegrambot.bot.handler: INFO

middle:
  service:
    url: http://localhost:8081/v2/middle