name: Java CI build&test with Gradle

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches: [ "trunk" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle Wrapper
        run: ./gradlew build
      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: Test report
          path: build/reports/tests/test
